/**
 * SeaDuelServer
 * SeaDuelServer
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from "@angular/core";
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpEvent
} from "@angular/common/http";
import { CustomHttpUrlEncodingCodec } from "../encoder";

import { Observable } from "rxjs";

import { Boat } from "../model/boat";
import { Game } from "../model/game";
import { Move } from "../model/move";

import { BASE_PATH, COLLECTION_FORMATS } from "../variables";
import { Configuration } from "../configuration";

@Injectable()
export class GamesService {
  protected basePath = "https://localhost/api/v1";
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  constructor(
    protected httpClient: HttpClient,
    @Optional()
    @Inject(BASE_PATH)
    basePath: string,
    @Optional() configuration: Configuration
  ) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath || configuration.basePath || this.basePath;
    }
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = "multipart/form-data";
    for (let consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }

  /**
   *
   * Adds a new boat during initial positioning
   * @param id The user id of the opponent
   * @param body The boat to add
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public usersByIdIdGameBoatsPost(
    id: string,
    body: Boat,
    observe?: "body",
    reportProgress?: boolean
  ): Observable<any>;
  public usersByIdIdGameBoatsPost(
    id: string,
    body: Boat,
    observe?: "response",
    reportProgress?: boolean
  ): Observable<HttpResponse<any>>;
  public usersByIdIdGameBoatsPost(
    id: string,
    body: Boat,
    observe?: "events",
    reportProgress?: boolean
  ): Observable<HttpEvent<any>>;
  public usersByIdIdGameBoatsPost(
    id: string,
    body: Boat,
    observe: any = "body",
    reportProgress: boolean = false
  ): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error(
        "Required parameter id was null or undefined when calling usersByIdIdGameBoatsPost."
      );
    }
    if (body === null || body === undefined) {
      throw new Error(
        "Required parameter body was null or undefined when calling usersByIdIdGameBoatsPost."
      );
    }

    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.apiKeys["Authorization"]) {
      headers = headers.set(
        "Authorization",
        this.configuration.apiKeys["Authorization"]
      );
    }

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ["application/json"];
    let httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set("Accept", httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    let consumes: string[] = ["application/json"];
    let httpContentTypeSelected:
      | string
      | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set("Content-Type", httpContentTypeSelected);
    }

    return this.httpClient.post<any>(
      `${this.basePath}/users/byId/${encodeURIComponent(
        String(id)
      )}/game/boats`,
      body,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   *
   * Resign from a game, that game will be counted as lost for the user and won for the opponent
   * @param id The user id of the opponent
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public usersByIdIdGameDelete(
    id: string,
    observe?: "body",
    reportProgress?: boolean
  ): Observable<any>;
  public usersByIdIdGameDelete(
    id: string,
    observe?: "response",
    reportProgress?: boolean
  ): Observable<HttpResponse<any>>;
  public usersByIdIdGameDelete(
    id: string,
    observe?: "events",
    reportProgress?: boolean
  ): Observable<HttpEvent<any>>;
  public usersByIdIdGameDelete(
    id: string,
    observe: any = "body",
    reportProgress: boolean = false
  ): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error(
        "Required parameter id was null or undefined when calling usersByIdIdGameDelete."
      );
    }

    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.apiKeys["Authorization"]) {
      headers = headers.set(
        "Authorization",
        this.configuration.apiKeys["Authorization"]
      );
    }

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ["application/json"];
    let httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set("Accept", httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    let consumes: string[] = ["application/json"];

    return this.httpClient.delete<any>(
      `${this.basePath}/users/byId/${encodeURIComponent(String(id))}/game`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   *
   * Get the game status with the specified opponent
   * @param id The user id of the opponent
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public usersByIdIdGameGet(
    id: string,
    observe?: "body",
    reportProgress?: boolean
  ): Observable<Game>;
  public usersByIdIdGameGet(
    id: string,
    observe?: "response",
    reportProgress?: boolean
  ): Observable<HttpResponse<Game>>;
  public usersByIdIdGameGet(
    id: string,
    observe?: "events",
    reportProgress?: boolean
  ): Observable<HttpEvent<Game>>;
  public usersByIdIdGameGet(
    id: string,
    observe: any = "body",
    reportProgress: boolean = false
  ): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error(
        "Required parameter id was null or undefined when calling usersByIdIdGameGet."
      );
    }

    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.apiKeys["Authorization"]) {
      headers = headers.set(
        "Authorization",
        this.configuration.apiKeys["Authorization"]
      );
    }

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ["application/json"];
    let httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set("Accept", httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    let consumes: string[] = ["application/json"];

    return this.httpClient.get<Game>(
      `${this.basePath}/users/byId/${encodeURIComponent(String(id))}/game`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   *
   * Fires a shot into the opponent board
   * @param id The user id of the opponent
   * @param body
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public usersByIdIdGameMovesPost(
    id: string,
    body: Move,
    observe?: "body",
    reportProgress?: boolean
  ): Observable<any>;
  public usersByIdIdGameMovesPost(
    id: string,
    body: Move,
    observe?: "response",
    reportProgress?: boolean
  ): Observable<HttpResponse<any>>;
  public usersByIdIdGameMovesPost(
    id: string,
    body: Move,
    observe?: "events",
    reportProgress?: boolean
  ): Observable<HttpEvent<any>>;
  public usersByIdIdGameMovesPost(
    id: string,
    body: Move,
    observe: any = "body",
    reportProgress: boolean = false
  ): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error(
        "Required parameter id was null or undefined when calling usersByIdIdGameMovesPost."
      );
    }
    if (body === null || body === undefined) {
      throw new Error(
        "Required parameter body was null or undefined when calling usersByIdIdGameMovesPost."
      );
    }

    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.apiKeys["Authorization"]) {
      headers = headers.set(
        "Authorization",
        this.configuration.apiKeys["Authorization"]
      );
    }

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ["application/json"];
    let httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set("Accept", httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    let consumes: string[] = ["application/json"];
    let httpContentTypeSelected:
      | string
      | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set("Content-Type", httpContentTypeSelected);
    }

    return this.httpClient.post<any>(
      `${this.basePath}/users/byId/${encodeURIComponent(
        String(id)
      )}/game/moves`,
      body,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   *
   * Send a new game request to an user
   * @param id The user id of the opponent
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public usersByIdIdGamePost(
    id: string,
    observe?: "body",
    reportProgress?: boolean
  ): Observable<any>;
  public usersByIdIdGamePost(
    id: string,
    observe?: "response",
    reportProgress?: boolean
  ): Observable<HttpResponse<any>>;
  public usersByIdIdGamePost(
    id: string,
    observe?: "events",
    reportProgress?: boolean
  ): Observable<HttpEvent<any>>;
  public usersByIdIdGamePost(
    id: string,
    observe: any = "body",
    reportProgress: boolean = false
  ): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error(
        "Required parameter id was null or undefined when calling usersByIdIdGamePost."
      );
    }

    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.apiKeys["Authorization"]) {
      headers = headers.set(
        "Authorization",
        this.configuration.apiKeys["Authorization"]
      );
    }

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ["application/json"];
    let httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set("Accept", httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    let consumes: string[] = ["application/json"];

    return this.httpClient.post<any>(
      `${this.basePath}/users/byId/${encodeURIComponent(String(id))}/game`,
      null,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   *
   * Accept a game request from an user
   * @param id The user id of the opponent
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public usersByIdIdGamePut(
    id: string,
    observe?: "body",
    reportProgress?: boolean
  ): Observable<any>;
  public usersByIdIdGamePut(
    id: string,
    observe?: "response",
    reportProgress?: boolean
  ): Observable<HttpResponse<any>>;
  public usersByIdIdGamePut(
    id: string,
    observe?: "events",
    reportProgress?: boolean
  ): Observable<HttpEvent<any>>;
  public usersByIdIdGamePut(
    id: string,
    observe: any = "body",
    reportProgress: boolean = false
  ): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error(
        "Required parameter id was null or undefined when calling usersByIdIdGamePut."
      );
    }

    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.apiKeys["Authorization"]) {
      headers = headers.set(
        "Authorization",
        this.configuration.apiKeys["Authorization"]
      );
    }

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ["application/json"];
    let httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set("Accept", httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    let consumes: string[] = ["application/json"];

    return this.httpClient.put<any>(
      `${this.basePath}/users/byId/${encodeURIComponent(String(id))}/game`,
      null,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }
}
