/**
 * SeaDuelServer
 * SeaDuelServer
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GameAvailableBoats } from "./gameAvailableBoats";
import { OpponentBoard } from "./opponentBoard";
import { PlayerBoard } from "./playerBoard";

export interface Game {
  playerId?: string;
  opponentId?: string;
  state?: Game.StateEnum;
  /**
   * UserId of the winner, -1 if still playing
   */
  winnerId?: string;
  playerBoard?: PlayerBoard;
  opponentBoard?: OpponentBoard;
  /**
   * If the player has positioned his boats
   */
  playerReady?: boolean;
  /**
   * If the opponent has positioned his boats
   */
  opponentReady?: boolean;
  /**
   * Time when the game first started
   */
  startTime?: Date;
  availableBoats?: Array<GameAvailableBoats>;
}
export namespace Game {
  export type StateEnum =
    | "WaitingForResponse"
    | "HasToRespond"
    | "BoatsPositioning"
    | "PlayerTurn"
    | "OpponentTurn"
    | "Ended";
  export const StateEnum = {
    WaitingForResponse: "WaitingForResponse" as StateEnum,
    HasToRespond: "HasToRespond" as StateEnum,
    BoatsPositioning: "BoatsPositioning" as StateEnum,
    PlayerTurn: "PlayerTurn" as StateEnum,
    OpponentTurn: "OpponentTurn" as StateEnum,
    Ended: "Ended" as StateEnum
  };
}
