/**
 * SeaDuelServer
 * SeaDuelServer
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GameBoard } from "./gameBoard";

export interface Game {
  state?: Game.StateEnum;
  /**
   * UserId of the winner, -1 if still playing
   */
  winnerId?: string;
  playerBoard?: GameBoard;
  opponentBoard?: GameBoard;
  /**
   * If the player has positioned his boats
   */
  playerReady?: boolean;
  /**
   * If the opponent has positioned his boats
   */
  opponentReady?: boolean;
  /**
   * Time when the game first started
   */
  startTime?: Date;
}
export namespace Game {
  export type StateEnum =
    | "WaitingForResponse"
    | "Rejected"
    | "BoatsPositioning"
    | "PlayerTurn"
    | "OpponentTurn"
    | "Ended";
  export const StateEnum = {
    WaitingForResponse: "WaitingForResponse" as StateEnum,
    Rejected: "Rejected" as StateEnum,
    BoatsPositioning: "BoatsPositioning" as StateEnum,
    PlayerTurn: "PlayerTurn" as StateEnum,
    OpponentTurn: "OpponentTurn" as StateEnum,
    Ended: "Ended" as StateEnum
  };
}
