/**
 * SeaDuelServer
 * SeaDuelServer
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Message {
    /**
     * The body of the message
     */
    content: string;
    /**
     * When the message have been received by the server
     */
    time: Date;
    /**
     * User id of the sender
     */
    senderId: string;
    /**
     * User id of the receiver
     */
    recipientId: string;
}
