/**
 * SeaDuelServer
 * SeaDuelServer
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PlayerBoardBoardData } from './playerBoardBoardData';


export interface PlayerBoard {
    /**
     * 10 by default
     */
    width: number;
    /**
     * 10 by default
     */
    height: number;
    boardData: Array<PlayerBoardBoardData>;
}
