/**
 * SeaDuelServer
 * SeaDuelServer
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface PlayerBoardBoardData {
  type: PlayerBoardBoardData.TypeEnum;
  /**
   * True if that cell was attacked by the opponent
   */
  checked: boolean;
}
export namespace PlayerBoardBoardData {
  export type TypeEnum =
    | "Empty"
    | "Destroyer"
    | "Submarine"
    | "Battleship"
    | "AircraftCarrier";
  export const TypeEnum = {
    Empty: "Empty" as TypeEnum,
    Destroyer: "Destroyer" as TypeEnum,
    Submarine: "Submarine" as TypeEnum,
    Battleship: "Battleship" as TypeEnum,
    AircraftCarrier: "AircraftCarrier" as TypeEnum
  };
}
