/**
 * SeaDuelServer
 * SeaDuelServer
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface User {
    /**
     * Username
     */
    id?: string;
    email?: string;
    password?: string;
    role?: User.RoleEnum;
    registrationDate?: Date;
    state?: User.StateEnum;
    /**
     * Won or opponent resigned
     */
    wonGames?: number;
    /**
     * Lost or withdrawn
     */
    lostGames?: number;
    /**
     * Position in ranking, calculated with won and lost games ratio
     */
    position?: number;
    /**
     * Last http request made by user, for online check
     */
    lastActivity?: Date;
    /**
     * True if the user is playing a game with someone
     */
    playing?: boolean;
    /**
     * True if there are messages coming from that user
     */
    hasUnreadMessages?: boolean;
    /**
     * True if there are games coming from that user
     */
    hasUnreadGames?: boolean;
}
export namespace User {
    export type RoleEnum = 'user' | 'administrator';
    export const RoleEnum = {
        User: 'user' as RoleEnum,
        Administrator: 'administrator' as RoleEnum
    }
    export type StateEnum = 'offline' | 'online';
    export const StateEnum = {
        Offline: 'offline' as StateEnum,
        Online: 'online' as StateEnum
    }
}
