/**
 * SeaDuelServer
 * SeaDuelServer
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface User {
  /**
   * Username
   */
  id?: string;
  email?: string;
  password?: string;
  role?: User.RoleEnum;
  registrationDate?: Date;
  state?: User.StateEnum;
  wonGames?: number;
  /**
   * Lost or withdrawn
   */
  lostGames?: number;
  /**
   * Position in ranking
   */
  position?: number;
  /**
   * Last http request made by user, for online check
   */
  lastActivity?: Date;
  playing?: boolean;
}
export namespace User {
  export type RoleEnum = "user" | "administrator";
  export const RoleEnum = {
    User: "user" as RoleEnum,
    Administrator: "administrator" as RoleEnum
  };
  export type StateEnum = "offline" | "online";
  export const StateEnum = {
    Offline: "offline" as StateEnum,
    Online: "online" as StateEnum
  };
}
